Repository YunWonYong/Programmers, pull requests merged in 2021-11, with the labels that each got.

#57 Programmers Level 1 , K번째수
  Algorithms/src/andy/javascript/level1/KstNumber.js
  Algorithms/src/andy/level1/KstNumber.java
Labels: branch nattybear, approve

#60 프로그래머스 Level 1, 완주하지 못한 선수
  Algorithms/src/andy/javascript/level1/UnfinishedPlayer.js
  Algorithms/src/andy/level1/UnfinishedPlayer.java
Labels: approve

#62 Close #52 #53 #54
  Algorithms/src/nattybear/level1/FailedPlayer.java
  Algorithms/src/nattybear/level1/FailedPlayer.js
  Algorithms/src/nattybear/level1/KthNumber.java
  Algorithms/src/nattybear/level1/KthNumber.js
  Algorithms/src/nattybear/level1/MakePrime.java
  Algorithms/src/nattybear/level1/MakePrime.js
Labels: branch ywy, approve

#63 프로그래머스 Level 1, 소수만들기
  Algorithms/src/andy/javascript/level1/MakePrimeNumber.js
  Algorithms/src/andy/level1/MakePrimeNumber.java
Labels: branch andy, merge

#69 프로그래머스 Level 1,폰켓몬
  Algorithms/src/andy/javascript/level1/Pokemon.js
  Algorithms/src/andy/level1/Pokemon.java
Labels: branch andy, merge

#72 프로그래머스 Level 1,체육복
  Algorithms/src/andy/javascript/level1/SportsUniform.js
  Algorithms/src/andy/level1/SportsUniform.java
Labels: approve

#73 Clear #65 #66 #67
  Algorithms/src/nattybear/level1/GymSuit.java
  Algorithms/src/nattybear/level1/GymSuit.js
  Algorithms/src/nattybear/level1/MathDumb.java
  Algorithms/src/nattybear/level1/MathDumb.js
  Algorithms/src/nattybear/level1/Ponkemon.java
  Algorithms/src/nattybear/level1/Ponkemon.js
Labels: merge, branch nattybear

#84 Clear #75 #76 #77
  Algorithms/src/nattybear/level1/Base3.java
  Algorithms/src/nattybear/level1/Base3.js
  Algorithms/src/nattybear/level1/FailRate.java
  Algorithms/src/nattybear/level1/FailRate.js
  Algorithms/src/nattybear/level1/SumDiv.java
  Algorithms/src/nattybear/level1/SumDiv.js
Labels: merge, branch nattybear

#90 2021-11-22 #86 clear, #87 clear, #88 clear
  Algorithms/src/andy/javascript/level1/budget.js
  Algorithms/src/andy/javascript/level1/twopickplus.js
  Algorithms/src/andy/javascript/level1/year2016.js
  Algorithms/src/andy/level1/twopickplus.java
  Algorithms/src/andy/level1/year2016.java
  Algorithms/src/budget/budget.java
Labels: merge

#91 Clear #86 #87 #88
  Algorithms/src/nattybear/level1/2016.js
  Algorithms/src/nattybear/level1/Budget.java
  Algorithms/src/nattybear/level1/Budget.js
  Algorithms/src/nattybear/level1/ChooseTwo.java
  Algorithms/src/nattybear/level1/ChooseTwo.js
  Algorithms/src/nattybear/level1/TwoOSixteen.java
Labels: merge
