Repository YunWonYong/Programmers, pull requests merged in 2021-12, with the labels that each got.

#96 2021-11-27 #93 clear
  Algorithms/src/ywy/java/level1/MinimumRectangle.java
  Algorithms/src/ywy/java/level1/test/MinimumRectangleTest.java
  Algorithms/src/ywy/javascript/level1/MinimumRectangle.js
Labels: approve

#99 Clear #93 #94 #95
  Algorithms/src/nattybear/level1/Amusement.java
  Algorithms/src/nattybear/level1/Amusement.js
  Algorithms/src/nattybear/level1/Rect.java
  Algorithms/src/nattybear/level1/Rect.js
  Algorithms/src/nattybear/level1/Remainder.java
  Algorithms/src/nattybear/level1/Remainder.js
Labels: merge

#104 2021-12-05 #101 Clear
  Algorithms/src/ywy/java/level1/SecretMap.java
  Algorithms/src/ywy/java/level1/test/FirstWeekOfDecember.java
  Algorithms/src/ywy/java/level1/test/SecretMapTest.java
  Algorithms/src/ywy/javascript/level1/SecretMap.js
Labels: approve

#106 2021-12-05 #103 clear
  Algorithms/src/ywy/java/level1/DartsGame.java
  Algorithms/src/ywy/java/level1/test/DartsGameTest.java
  Algorithms/src/ywy/javascript/level1/DartsGame.js
Labels: approve

#108 Clear #101 #102 #103
  Algorithms/src/nattybear/level1/Center.java
  Algorithms/src/nattybear/level1/Center.js
  Algorithms/src/nattybear/level1/Dart.java
  Algorithms/src/nattybear/level1/Dart.js
  Algorithms/src/nattybear/level1/SecretMap.java
  Algorithms/src/nattybear/level1/SecretMap.js
Labels: merge

#123 Clear #109 #110 #111
  Algorithms/src/nattybear/level1/.gitignore
  Algorithms/src/nattybear/level1/Divisor.hs
  Algorithms/src/nattybear/level1/Divisor.java
  Algorithms/src/nattybear/level1/Divisor.js
  Algorithms/src/nattybear/level1/SumTwo.hs
  Algorithms/src/nattybear/level1/SumTwo.java
  Algorithms/src/nattybear/level1/SumTwo.js
  Algorithms/src/nattybear/level1/Unique.hs
  Algorithms/src/nattybear/level1/Unique.java
  Algorithms/src/nattybear/level1/Unique.js
Labels: branch ywy, branch nattybear, approve, branch suhyun, branch ljh

#117 2021-12-14 ywy #110 clear
  Algorithms/src/ywy/java/level1/DivisibleNumber.java
  Algorithms/src/ywy/java/level1/test/cases/DivisibleNumberTest.java
  Algorithms/src/ywy/javascript/level1/DivisibleNumber.js
Labels: branch nattybear, approve, branch ljh

#118 2021-12-14 #109 #110 #111 Clear
  Algorithms/src/suhyun/java/ContinuousNumber_109.java
  Algorithms/src/suhyun/java/Division_110.java
  Algorithms/src/suhyun/java/Hap_111.java
  Algorithms/src/suhyun/js/ContinuousNumber_109.js
  Algorithms/src/suhyun/js/Division_110.js
  Algorithms/src/suhyun/js/Hap_111.js
Labels: merge

#116 2021-12-14 ywy #109 clear
  Algorithms/src/ywy/java/level1/HateSameNumber.java
  Algorithms/src/ywy/java/level1/test/DecemberWeekOf2.java
  Algorithms/src/ywy/java/level1/test/cases/HateSameNumberTest.java
  Algorithms/src/ywy/javascript/level1/HateSameNumber.js
Labels: merge

#121 2021-12-14 andy #109 clear, #110 clear, #111 clear
  Algorithms/src/andy/javascript/level1/DivideNumberArray.js
  Algorithms/src/andy/javascript/level1/EqualNumberNo.js
  Algorithms/src/andy/javascript/level1/TwoNumberSum.js
  Algorithms/src/andy/level1/DivideNumberArray.java
  Algorithms/src/andy/level1/EqualNumberNo.java
  Algorithms/src/andy/level1/TwoNumberSum.java
Labels: merge

#131 2021-12-19 repository renewal into ywy
  .gitignore
Labels: branch nattybear, approve, branch suhyun, branch ljh

#133 2021-12-21 ywy add java, js
  Ywy/JAVA/src/level1/MyWaySorting.java
  Ywy/JAVA/src/level1/PAndYCount.java
  Ywy/JAVA/src/level1/StringDescending.java
  Ywy/JAVA/src/level1/test/AllTests.java
  Ywy/JAVA/src/level1/test/DecemberWeekOf3.java
  Ywy/JAVA/src/level1/test/cases/MyWaySortingTest.java
  Ywy/JAVA/src/level1/test/cases/PAndYCountTest.java
  Ywy/JAVA/src/level1/test/cases/StringDescendingTest.java
  Ywy/JavaScript/level1/MyWaySorting.js
  Ywy/JavaScript/level1/PAndYCount.js
  Ywy/JavaScript/level1/StringDescending.js
  Ywy/JavaScript/level1/test/MyWaySorting.test.js
  Ywy/JavaScript/level1/test/PAndYCount.test.js
  Ywy/JavaScript/level1/test/StringDescending.test.js
Labels: approve

#137 Andy : 문자열 내 마음대로 정렬하기,문자열 내 p와 y의 개수,문자열 내림차순으로 배치하기
  Andy/src/level1/java/StringPYCount.java
  Andy/src/level1/java/StringSortInverse.java
  Andy/src/level1/java/StringSortMine.java
  Andy/src/level1/javascript/StringPYCount.js
  Andy/src/level1/javascript/StringSortInverse.js
  Andy/src/level1/javascript/StringSortMine.js
Labels: merge

#139 Suhyun:12월 4주차
  Suhyun/JS/Naerim.js
  Suhyun/JS/Omoikiri.js
  Suhyun/JS/PtoY.js
  Suhyun/Java/Naerim.java
  Suhyun/Java/Omoikiri.java
  Suhyun/Java/PtoY.java
Labels: approve

#143 Create action that adds label to PR
  .github/workflows/add-approve.yml
  .github/workflows/add-reviewer.yml
  .github/workflows/remove-merge.yml
  .github/workflows/remove-reviewer.yml
  .github/workflows/remove-sender.yml
  .github/workflows/script/add-approve.py
  .github/workflows/script/add-reviewer.py
  .github/workflows/script/label.py
  .github/workflows/script/remove-merge.py
  .github/workflows/script/remove-reviewer.py
  .github/workflows/script/remove-sender.py
Labels: merge

#144 Solve lessons
  nattybear/level1/문자열-다루기-기본/Solution.java
  nattybear/level1/문자열-다루기-기본/solution.js
  nattybear/level1/서울에서-김서방-찾기/Solution.java
  nattybear/level1/서울에서-김서방-찾기/solution.js
  nattybear/level1/소수-찾기/Solution.java
  nattybear/level1/소수-찾기/solution.js
Labels: merge

#149 solve problems(211224 - 211230)
  ljh/java/src/level1/FindKim.java
  ljh/java/src/level1/HandlingString.java
  ljh/java/src/level1/SearchPrimeNumber.java
  ljh/java/src/level1/test/FindKimTest.java
  ljh/java/src/level1/test/HandlingStringTest.java
  ljh/java/src/level1/test/SearchPrimeNumberTest.java
  ljh/javascript/level1/FindKim.js
  ljh/javascript/level1/HandlingString.js
  ljh/javascript/level1/SearchPrimeNumber.js
  ljh/javascript/level1/test/FindKim.test.js
  ljh/javascript/level1/test/HandlingString.test.js
  ljh/javascript/level1/test/SearchPrimeNumber.test.js
Labels: merge

#150 2021-12-29 Andy
  Andy/src/level1/etc/basicString.cpp
  Andy/src/level1/etc/basicString.cs
  Andy/src/level1/etc/basicString.py
  Andy/src/level1/etc/findPrimeNumber.cs
  Andy/src/level1/etc/findPrimeNumber.py
  Andy/src/level1/etc/finidPrimeNumber.cpp
  Andy/src/level1/etc/seoulKim.cpp
  Andy/src/level1/etc/seoulKim.cs
  Andy/src/level1/etc/seoulKim.py
  Andy/src/level1/java/basicString.java
  Andy/src/level1/java/findPrimeNumber.java
  Andy/src/level1/java/seoulKim.java
  Andy/src/level1/javascript/basicString.js
  Andy/src/level1/javascript/findPrimeNumber.js
  Andy/src/level1/javascript/seoulKim.js
Labels: merge
