Repository YunWonYong/Programmers, pull requests merged in 2022-01, with the labels that each got.

#153 Solve lessons
  nattybear/level1/문자열을-정수로-바꾸기/Solution.java
  nattybear/level1/문자열을-정수로-바꾸기/solution.js
  nattybear/level1/수박수박수박수박수박수?/Solution.java
  nattybear/level1/수박수박수박수박수박수?/solution.js
  nattybear/level1/시저-암호/Solution.java
  nattybear/level1/시저-암호/solution.js
Labels: merge

#154 Suhyun: 1월 1주차
  Suhyun/.vscode/launch.json
  Suhyun/.vscode/settings.json
  Suhyun/Level1/12월 5주차/문자열 다루기 기본/String_Control_Default.js
  Suhyun/Level1/1월 1주차/문자열 정수로 바꾸기/ChangeStringtoInteger.java
  Suhyun/Level1/1월 1주차/문자열 정수로 바꾸기/ChangeStringtoInteger.js
  Suhyun/Level1/1월 1주차/수박수/Subac.java
  Suhyun/Level1/1월 1주차/수박수/Subac.js
  Suhyun/Level1/1월 1주차/시저암호/Caesar.java
  Suhyun/Level1/1월 1주차/시저암호/Caesar.js
Labels: merge

#158 2022-01-05 Andy
  Andy/src/level1/java/caesarpassword.java
  Andy/src/level1/java/stringtoint.java
  Andy/src/level1/java/subak.java
  Andy/src/level1/javascript/caesarpassword.js
  Andy/src/level1/javascript/stringtoint.js
  Andy/src/level1/javascript/subak.js
Labels: approve, branch Lee-jh01

#162 Resolve #161
  .github/workflows/script/remove-sender.py
  nattybear/level1/수박/Solution.java
  nattybear/level1/수박/solution.js
Labels: merge

#160 solve problems
  ljh/java/src/level1/CaesarCipher.java
  ljh/java/src/level1/StringToInteger.java
  ljh/java/src/level1/SubakSubak.java
  ljh/java/src/level1/test/CaesarCipherTest.java
  ljh/java/src/level1/test/StringToIntegerTest.java
  ljh/java/src/level1/test/SubakSubakTest.java
  ljh/javascript/level1/CaesarCipher.js
  ljh/javascript/level1/StringToInteger.js
  ljh/javascript/level1/SubakSubak.js
  ljh/javascript/level1/test/CaesarCipher.test.js
  ljh/javascript/level1/test/StringToInteger.test.js
  ljh/javascript/level1/test/SubakSubak.test.js
Labels: merge

#163 Suhyun : 1월 2주차
  Suhyun/.vscode/launch.json
  Suhyun/.vscode/settings.json
  Suhyun/Level1/1월 2주차/약수의 합/Yaksu_hap.java
  Suhyun/Level1/1월 2주차/약수의 합/Yaksu_hap.js
  Suhyun/Level1/1월 2주차/이상한 문자 만들기/Okasii_mozi.java
  Suhyun/Level1/1월 2주차/이상한 문자 만들기/Okasii_mozi.js
  Suhyun/Level1/1월 2주차/자릿수 더하기/Add_digit.java
  Suhyun/Level1/1월 2주차/자릿수 더하기/Add_digit.js
  Suhyun/Level1/1월 2주차/자연수 뒤집어 배열로 만들기/Reverse_number.java
  Suhyun/Level1/1월 2주차/자연수 뒤집어 배열로 만들기/Reverse_number.js
Labels: merge

#164 2022-01-12 ywy
  Ywy/JAVA/src/level1/AddDigits.java
  Ywy/JAVA/src/level1/ArrayByFlippingNumbers.java
  Ywy/JAVA/src/level1/SumOfFactors.java
  Ywy/JAVA/src/level1/WeirdStringMake.java
  Ywy/JAVA/src/level1/test/AllTests.java
  Ywy/JAVA/src/level1/test/JanuaryWeekOf2.java
  Ywy/JAVA/src/level1/test/cases/AddDigitsTest.java
  Ywy/JAVA/src/level1/test/cases/ArrayByFlippingNumbersTest.java
  Ywy/JAVA/src/level1/test/cases/SumOfFactorsTest.java
  Ywy/JAVA/src/level1/test/cases/WeirdStringMakeTest.java
  Ywy/JavaScript/level1/AddDigits.js
  Ywy/JavaScript/level1/ArrayByFlippingNumbers.js
  Ywy/JavaScript/level1/SumOfFactors.js
  Ywy/JavaScript/level1/WeirdStringMake.js
  Ywy/JavaScript/level1/test/AddDigits.test.js
  Ywy/JavaScript/level1/test/ArrayByFlippingNumbers.test.js
  Ywy/JavaScript/level1/test/SumOfFactors.test.js
  Ywy/JavaScript/level1/test/WeirdStringMake.test.js
Labels: merge

#165 Solve lessons
  nattybear/level1/약수의-합/Solution.java
  nattybear/level1/약수의-합/solution.c
  nattybear/level1/약수의-합/solution.js
  nattybear/level1/이상한-문자-만들기/Solution.java
  nattybear/level1/이상한-문자-만들기/solution.js
  nattybear/level1/자릿수-더하기/Solution.java
  nattybear/level1/자릿수-더하기/solution.js
  nattybear/level1/자연수-뒤집어-배열로-만들기/Solution.java
  nattybear/level1/자연수-뒤집어-배열로-만들기/solution.js
Labels: merge

#166 solve problems _ljh
  ljh/java/src/level1/MakeStrangeText.java
  ljh/java/src/level1/ReverseNumber.java
  ljh/java/src/level1/SumOfDigit.java
  ljh/java/src/level1/SumOfDivisor.java
  ljh/java/src/level1/test/MakeStrangeTextTest.java
  ljh/java/src/level1/test/ReverseNumberTest.java
  ljh/java/src/level1/test/SumOfDigitTest.java
  ljh/java/src/level1/test/SumOfDivisorTest.java
  ljh/javascript/level1/MakeStrangeText.js
  ljh/javascript/level1/ReverseNumber.js
  ljh/javascript/level1/SumOfDigit.js
  ljh/javascript/level1/SumOfDivisor.js
  ljh/javascript/level1/test/MakeStrangeText.test.js
  ljh/javascript/level1/test/ReverseNumber.test.js
  ljh/javascript/level1/test/SumOfDigit.test.js
  ljh/javascript/level1/test/SumOfDivisor.test.js
Labels: merge

#167 2022-01-14 Andy
  Andy/src/level1/java/DivisorSum.java
  Andy/src/level1/java/NumberReverseArray.java
  Andy/src/level1/java/NumberSum.java
  Andy/src/level1/java/StrangeString.java
  Andy/src/level1/javascript/DivisorSum.js
  Andy/src/level1/javascript/NumberReverseArray.js
  Andy/src/level1/javascript/NumberSum.js
  Andy/src/level1/javascript/StrangeString.js
Labels: merge

#168 solve problems_ljh
  ljh/java/src/level1/ArrangeIntegerInDescendingOrder.java
  ljh/java/src/level1/EvenAndOdd.java
  ljh/java/src/level1/IsIntegerSquareRoot.java
  ljh/java/src/level1/RemoveSmallestNumber.java
  ljh/java/src/level1/test/ArrangeIntegerInDescendingOrderTest.java
  ljh/java/src/level1/test/EvenAndOddTest.java
  ljh/java/src/level1/test/IsIntegerSquareRootTest.java
  ljh/java/src/level1/test/RemoveSmallestNumberTest.java
  ljh/javascript/level1/ArrangeIntegerInDescendingOrder.js
  ljh/javascript/level1/EvenAndOdd.js
  ljh/javascript/level1/IsIntegerSquareRoot.js
  ljh/javascript/level1/RemoveSmallestNumber.js
  ljh/javascript/level1/test/ArrangeIntegerInDescendingOrder.test.js
  ljh/javascript/level1/test/EvenAndOdd.test.js
  ljh/javascript/level1/test/IsIntegerSquareRoot.test.js
  ljh/javascript/level1/test/RemoveSmallestNumber.test.js
Labels: approve

#172 Solve lessons
  nattybear/level1/정수-내림차순으로-배치하기/Solution.java
  nattybear/level1/정수-내림차순으로-배치하기/solution.js
  nattybear/level1/정수-제곱근-판별/Solution.java
  nattybear/level1/정수-제곱근-판별/solution.js
  nattybear/level1/제일-작은-수-제거하기/Solution.java
  nattybear/level1/제일-작은-수-제거하기/solution.js
  nattybear/level1/짝수와-홀수/Solution.java
  nattybear/level1/짝수와-홀수/solution.js
Labels: merge, branch suhyun96

#171 1월 3주차
  Suhyun/Level1/1월 2주차/이상한 문자 만들기/Okasii_mozi.java
  Suhyun/Level1/1월 2주차/이상한 문자 만들기/Okasii_mozi.js
  Suhyun/Level1/1월 2주차/자릿수 더하기/Add_digit.java
  Suhyun/Level1/1월 2주차/자연수 뒤집어 배열로 만들기/Reverse_number.js
  Suhyun/Level1/1월 3주차/정수 내림차순으로 배치하기/ReverseNumber.java
  Suhyun/Level1/1월 3주차/정수 내림차순으로 배치하기/ReverseNumber.js
  Suhyun/Level1/1월 3주차/정수 제곱근 판별/SquareRoot.class
  Suhyun/Level1/1월 3주차/정수 제곱근 판별/SquareRoot.java
  Suhyun/Level1/1월 3주차/정수 제곱근 판별/SquareRoot.js
  Suhyun/Level1/1월 3주차/제일 작은 수 제거하기/DeleteSmallNumber.class
  Suhyun/Level1/1월 3주차/제일 작은 수 제거하기/DeleteSmallNumber.java
  Suhyun/Level1/1월 3주차/제일 작은 수 제거하기/DeleteSmallNumber.js
  Suhyun/Level1/1월 3주차/짝수와 홀수/OddEven.class
  Suhyun/Level1/1월 3주차/짝수와 홀수/OddEven.java
  Suhyun/Level1/1월 3주차/짝수와 홀수/OddEven.js
Labels: merge

#169 2022-01-16 ywy
  Ywy/Go/level1/정수 내림차순으로 배치하기/NumberDescSort.go
  Ywy/Go/level1/정수 제곱근 판별/NumberSquareRootDiscrimination.go
  Ywy/Go/level1/제일 작은 수 제거하기/MinNumberRemove.go
  Ywy/Go/level1/짝수와홀수/EvenAndOdd.go
  Ywy/JAVA/src/level1/EvenAndOdd.java
  Ywy/JAVA/src/level1/MinNumberRemove.java
  Ywy/JAVA/src/level1/NumberDescSort.java
  Ywy/JAVA/src/level1/NumberSquareRootDiscrimination.java
  Ywy/JAVA/src/level1/test/AllTests.java
  Ywy/JAVA/src/level1/test/JanuaryWeekOf3.java
  Ywy/JAVA/src/level1/test/cases/EvenAndOddTest.java
  Ywy/JAVA/src/level1/test/cases/MinNumberRemoveTest.java
  Ywy/JAVA/src/level1/test/cases/NumberDescSortTest.java
  Ywy/JAVA/src/level1/test/cases/NumberSquareRootDiscriminationTest.java
  Ywy/JavaScript/level1/EvenAndOdd.js
  Ywy/JavaScript/level1/MinNumberRemove.js
  Ywy/JavaScript/level1/NumberDescSort.js
  Ywy/JavaScript/level1/NumberSquareRootDiscrimination.js
  Ywy/JavaScript/level1/test/EvenAndOdd.test.js
  Ywy/JavaScript/level1/test/MinNumberRemove.test.js
  Ywy/JavaScript/level1/test/NumberDescSort.test.js
  Ywy/JavaScript/level1/test/NumberSquareRootDiscrimination.test.js
Labels: merge

#174 2022-01-22 ywy
  Ywy/Go/level1/N2승배열자르기/nRootArraySplit.go
  Ywy/Go/level1/N2승배열자르기/nRootArraySplit_test.go
  Ywy/Go/level1/최대공약수와최소공배수/gcdAndLcm.go
  Ywy/Go/level1/최대공약수와최소공배수/gcdAndLcm_test.go
  Ywy/Go/level1/콜라츠추측/colatzGuess.go
  Ywy/Go/level1/콜라츠추측/colatzGuess_test.go
  Ywy/Go/level1/평균구하기/average.go
  Ywy/Go/level1/평균구하기/average_test.go
  Ywy/Go/level1/하샤드수/harshadNumber.go
  Ywy/Go/level1/하샤드수/harshadNumber_test.go
  Ywy/JAVA/src/level1/ArrayNSqrt2Split.java
  Ywy/JAVA/src/level1/Average.java
  Ywy/JAVA/src/level1/ColatzGuess.java
  Ywy/JAVA/src/level1/GcdAndLcm.java
  Ywy/JAVA/src/level1/HarshadNumber.java
  Ywy/JAVA/src/level1/test/JanuaryWeekOf4.java
  Ywy/JAVA/src/level1/test/cases/ArrayNSqrt2SplitTest.java
  Ywy/JAVA/src/level1/test/cases/AverageTest.java
  Ywy/JAVA/src/level1/test/cases/ColatzGuessTest.java
  Ywy/JAVA/src/level1/test/cases/GcdAndLcmTest.java
  Ywy/JAVA/src/level1/test/cases/HarshadNumberTest.java
  Ywy/JavaScript/level1/ArrayNRootSplit.js
  Ywy/JavaScript/level1/Average.js
  Ywy/JavaScript/level1/ColatzGuess.js
  Ywy/JavaScript/level1/GcdAndLcm.js
  Ywy/JavaScript/level1/HarshadNumber.js
  Ywy/JavaScript/level1/test/ArrayNRootSplit.test.js
  Ywy/JavaScript/level1/test/Average.test.js
  Ywy/JavaScript/level1/test/ColatzGuess.test.js
  Ywy/JavaScript/level1/test/GcdAndLcm.test.js
  Ywy/JavaScript/level1/test/HarshadNumber.test.js
Labels: merge

#173 Solve lessons
  nattybear/level1/최대공약수와-최소공배수/Solution.java
  nattybear/level1/최대공약수와-최소공배수/solution.js
  nattybear/level1/콜라츠-추측/Solution.java
  nattybear/level1/콜라츠-추측/solution.js
  nattybear/level1/평균-구하기/Solution.java
  nattybear/level1/평균-구하기/solution.js
  nattybear/level1/하샤드-수/Solution.java
  nattybear/level1/하샤드-수/solution.js
Labels: merge

#177 Ljh
  ljh/java/src/level1/CalculateAverage.java
  ljh/java/src/level1/CollatzConjecture.java
  ljh/java/src/level1/GCDandLCM.java
  ljh/java/src/level1/GCDandLCM2.java
  ljh/java/src/level1/HarshadNumber.java
  ljh/java/src/level1/test/CalculateAverageTest.java
  ljh/java/src/level1/test/CollatzConjectureTest.java
  ljh/java/src/level1/test/GCDandLCDTest.java
  ljh/java/src/level1/test/HarshadNumberTest.java
  ljh/java/src/level2/SliceNSquaredArray.java
  ljh/java/src/level2/test/SliceNSquaredArrayTest.java
  ljh/javascript/level1/CalculateAverage.js
  ljh/javascript/level1/CollatzConjecture.js
  ljh/javascript/level1/GCDandLCM.js
  ljh/javascript/level1/HarshadNumber.js
  ljh/javascript/level1/test/CalculateAverage.test.js
  ljh/javascript/level1/test/CollatzConjecture.test.js
  ljh/javascript/level1/test/GCDandLCM.test.js
  ljh/javascript/level1/test/HarshadNumber.test.js
  ljh/javascript/level2/SliceNSquaredArray.js
  ljh/javascript/level2/test/SliceNSquareArray.test.js
Labels: approve

#176 1월 5째주
  Suhyun/Level1/1월 3주차/정수 내림차순으로 배치하기/ReverseNumber.java
  Suhyun/Level1/1월 3주차/정수 내림차순으로 배치하기/ReverseNumber.js
  Suhyun/Level1/1월 3주차/정수 제곱근 판별/SquareRoot.java
  Suhyun/Level1/1월 3주차/제일 작은 수 제거하기/DeleteSmallNumber.java
  Suhyun/Level1/1월 3주차/제일 작은 수 제거하기/DeleteSmallNumber.js
  Suhyun/Level1/1월 4주차/최대공약수와 최소공배수/MaximumPledgeMinimumMultiple.java
  Suhyun/Level1/1월 4주차/최대공약수와 최소공배수/ximumPledgeMinimumMultiple.js
  Suhyun/Level1/1월 4주차/콜라츠 추측/Collatz.class
  Suhyun/Level1/1월 4주차/콜라츠 추측/Collatz.java
  Suhyun/Level1/1월 4주차/콜라츠 추측/Collatz.js
  Suhyun/Level1/1월 4주차/평균구하기/Average.java
  Suhyun/Level1/1월 4주차/평균구하기/Average.js
  Suhyun/Level1/1월 4주차/하샤드수/Harshad.java
  Suhyun/Level1/1월 4주차/하샤드수/Harshad.js
  Suhyun/Level2/n^2 배열 자르기/N2array.java
  Suhyun/Level2/n^2 배열 자르기/N2array.js
Labels: merge

#178 2022-01-27 Andy
  Andy/src/level1/java/average.java
  Andy/src/level1/java/collatz.java
  Andy/src/level1/java/gcdlcm.java
  Andy/src/level1/java/harshad.java
  Andy/src/level1/javascript/average.js
  Andy/src/level1/javascript/collatz.js
  Andy/src/level1/javascript/gcdlcm.js
  Andy/src/level1/javascript/harshad.js
  Andy/src/level2/java/n2arraysplit.java
  Andy/src/level2/javascript/n2arraysplit.js
Labels: merge
