Repository YunWonYong/Programmers, pull requests merged in 2022-02, with the labels that each got.

#179 2022-02-02 ywy
  Ywy/Go/level1/x만큼간격이있는n개의숫자/nNumbersSpacedByX _test.go
  Ywy/Go/level1/x만큼간격이있는n개의숫자/nNumbersSpacedByX.go
  Ywy/Go/level1/직사각형별찍기/rectangleStar.go
  Ywy/Go/level1/핸드폰번호가리기/phoneNumberMasking.go
  Ywy/Go/level1/핸드폰번호가리기/phoneNumberMasking_test.go
  Ywy/Go/level1/행렬의덧샘/matrixSum.go
  Ywy/JAVA/src/level1/MatrixSum.java
  Ywy/JAVA/src/level1/NNumbersSpacedByX.java
  Ywy/JAVA/src/level1/PhoneNumberMasking.java
  Ywy/JAVA/src/level1/RectangleStar.java
  Ywy/JAVA/src/level1/test/AllTests.java
  Ywy/JAVA/src/level1/test/FebruaryWeekOf1.java
  Ywy/JAVA/src/level1/test/cases/MatrixSumTest.java
  Ywy/JAVA/src/level1/test/cases/NNumbersSpacedByXTest.java
  Ywy/JAVA/src/level1/test/cases/PhoneNumberMaskingTest.java
  Ywy/JavaScript/level1/MatrixSum.js
  Ywy/JavaScript/level1/NNumbersSpacedByX.js
  Ywy/JavaScript/level1/PhoneNumberMasking.js
  Ywy/JavaScript/level1/RectangleStar.js
  Ywy/JavaScript/level1/test/MatrixSum.test.js
  Ywy/JavaScript/level1/test/NNumbersSpacedByX.test.js
  Ywy/JavaScript/level1/test/PhoneNumberMasking.test.js
Labels: merge

#181 2022-02-03 Andy
  Andy/src/arrayAdd/arrayAdd.java
  Andy/src/level1/java/hidePhoneNumber.java
  Andy/src/level1/java/rectangleStar.java
  Andy/src/level1/java/reportResult.java
  Andy/src/level1/java/xnSpace.java
  Andy/src/level1/javascript/arrayAdd.js
  Andy/src/level1/javascript/hidePhoneNumber.js
  Andy/src/level1/javascript/rectangleStar.js
  Andy/src/level1/javascript/reportResult.js
  Andy/src/level1/javascript/xnSpace.js
Labels: merge

#182 2월 1주차
  Suhyun/Level1/1월 4주차/최대공약수와 최소공배수/MaximumPledgeMinimumMultiple.java
  Suhyun/Level1/1월 4주차/콜라츠 추측/Collatz.java
  Suhyun/Level1/1월 4주차/평균구하기/Average.js
  Suhyun/Level1/1월 4주차/하샤드수/Harshad.java
  Suhyun/Level1/2월 1주차/x만큼 간격이 있는 n개의 숫자/XspaceN.java
  Suhyun/Level1/2월 1주차/x만큼 간격이 있는 n개의 숫자/XspaceN.js
  Suhyun/Level1/2월 1주차/직사각형 별찍기/Squre_star.java
  Suhyun/Level1/2월 1주차/직사각형 별찍기/Squre_star.js
  Suhyun/Level1/2월 1주차/핸드폰 번호 가리기/Phone.class
  Suhyun/Level1/2월 1주차/핸드폰 번호 가리기/Phone.java
  Suhyun/Level1/2월 1주차/핸드폰 번호 가리기/Phone.js
  Suhyun/Level1/2월 1주차/행렬의 덧셈/Plus_array.class
  Suhyun/Level1/2월 1주차/행렬의 덧셈/Plus_array.java
  Suhyun/Level1/2월 1주차/행렬의 덧셈/Plus_array.js
Labels: merge

#183 solve problems_ljh
  ljh/java/src/level1/MatrixAddition.java
  ljh/java/src/level1/PhoneNumberMasking.java
  ljh/java/src/level1/PrintRectangleStar.java
  ljh/java/src/level1/Report.java
  ljh/java/src/level1/Report2.java
  ljh/java/src/level1/XMultiple.java
  ljh/javascript/level1/MatrixAddition.js
  ljh/javascript/level1/PhoneNumberMasking.js
  ljh/javascript/level1/PrintRectangleStar.js
  ljh/javascript/level1/Report.js
  ljh/javascript/level1/XMultiple.js
Labels: merge

#180 Solve lessons
  nattybear/level1/x만큼-간격이-있는-n개의-숫자/Solution.java
  nattybear/level1/x만큼-간격이-있는-n개의-숫자/solution.js
  nattybear/level1/직사각형-별찍기/Solution.java
  nattybear/level1/직사각형-별찍기/solution.js
  nattybear/level1/핸드폰-번호-가리기/Solution.java
  nattybear/level1/핸드폰-번호-가리기/solution.js
  nattybear/level1/행렬의-덧셈/Solution.java
  nattybear/level1/행렬의-덧셈/solution.js
Labels: merge

#186 2022-02-07 ywy
  Ywy/JAVA/src/level1/DartsGame.java
  Ywy/JAVA/src/level1/ReportResult.java
  Ywy/JAVA/src/level1/test/AllTests.java
  Ywy/JAVA/src/level1/test/FebruaryWeekOf2.java
  Ywy/JAVA/src/level1/test/cases/ReportResultTest.java
  Ywy/JAVA/src/level2/OpenChatRoom.java
  Ywy/JAVA/src/level2/StringCompression.java
  Ywy/JAVA/src/level2/test/AllTests.java
  Ywy/JAVA/src/level2/test/FebruaryWeekOf2.java
  Ywy/JAVA/src/level2/test/cases/OpenChatRoomTest.java
  Ywy/JAVA/src/level2/test/cases/StringCompressionTest.java
  Ywy/JavaScript/level1/ReportResult.js
  Ywy/JavaScript/level1/test/ReportResult.test.js
  Ywy/JavaScript/level2/OpenChatRoom.js
  Ywy/JavaScript/level2/StringCompression.js
  Ywy/JavaScript/level2/test/OpenChatRoom.test.js
  Ywy/JavaScript/level2/test/StringCompression.test.js
Labels: merge

#184 Solve lotto for the Crown
  nattybear/level1/로또의-최고-순위와-최저-순위/Solution.java
  nattybear/level1/로또의-최고-순위와-최저-순위/solution.js
Labels: merge

#185 Solve lessons
  nattybear/level1/신고-결과-받기/Solution.java
  nattybear/level1/신고-결과-받기/solution.js
  nattybear/level2/문자열-압축/Solution.java
  nattybear/level2/문자열-압축/solution.js
  nattybear/level2/오픈채팅방/Solution.java
  nattybear/level2/오픈채팅방/solution.js
Labels: merge

#193 220218 ljh
  ljh/level2/124 나라의 숫자/Solution.java
  ljh/level2/124 나라의 숫자/Solution.js
  ljh/level2/멀쩡한 사각형/Solution.java
  ljh/level2/멀쩡한 사각형/Solution.js
Labels: merge

#190 Solve lessons
  nattybear/level2/124-나라의-숫자/Solution.java
  nattybear/level2/124-나라의-숫자/solution.js
  nattybear/level2/멀쩡한-사각형/Solution.java
  nattybear/level2/멀쩡한-사각형/solution.js
Labels: merge

#194 22-02-18 suhyun
  Suhyun/Level1/신고 결과 받기/Solution.java
  Suhyun/Level1/신고 결과 받기/Solution.js
  Suhyun/Level2/1234나라의 숫자/Country124.js
  Suhyun/Level2/1234나라의 숫자/Country124_2.java
  Suhyun/Level2/멀쩡한 사각형/NomalSquare.java
  Suhyun/Level2/멀쩡한 사각형/NomalSquare.js
  Suhyun/Level2/문자열 압축/StringCompresion5.java
  Suhyun/Level2/문자열 압축/String_Compression2.js
  Suhyun/Level2/오픈채팅방/OpenChat.js
  Suhyun/Level2/오픈채팅방/OpenChat2.java
Labels: approve

#195 2202-02-21 ljh
  ljh/level2/기능 개발/Develop.java
  ljh/level2/기능 개발/Develop.js
  ljh/level2/기능 개발/DevelopQue.java
  ljh/level2/타겟 넘버/TargetNumber.java
  ljh/level2/타겟 넘버/TargetNumber.js
Labels: approve

#196 2022-02-21 ywy
  Ywy/Go/level2/기능개발/functionDevelopment.go
  Ywy/Go/level2/기능개발/functionDevelopment_test.go
  Ywy/Go/level2/타겟넘버/targetNumber.go
  Ywy/Go/level2/타겟넘버/targetNumber_test.go
  Ywy/JAVA/src/level2/FunctionDevelopment.java
  Ywy/JAVA/src/level2/TargetNumber.java
  Ywy/JAVA/src/level2/test/AllTests.java
  Ywy/JAVA/src/level2/test/FebruaryWeekOf4.java
  Ywy/JAVA/src/level2/test/cases/FunctionDevelopmentTest.java
  Ywy/JAVA/src/level2/test/cases/TargetNumberTest.java
  Ywy/JavaScript/level2/FunctionDevelopment.js
  Ywy/JavaScript/level2/TargetNumber.js
  Ywy/JavaScript/level2/test/FuntionDevelopment.test.js
  Ywy/JavaScript/level2/test/TargetNumber.test.js
Labels: merge

#199 2월 3주차 문제
  Suhyun/Level2/기능개발/Function.java
  Suhyun/Level2/기능개발/Function.js
  Suhyun/Level2/타겟넘버/TargetNumber.java
  Suhyun/Level2/타겟넘버/TargetNumber.js
Labels: approve, branch gmake20
